import Head from 'next/head'
import {
  Heading,
  Input,
  Textarea,
  Button,
  FormControl,
  FormLabel,
  Box,
  Text,
  HStack,
  Radio,
  RadioGroup,
  Container,
} from "@chakra-ui/react";

const CreateTodo = () => {
  return (
    <>
      <Head>
        <title>Create</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Box bg='yellow.200' w='100%' p={3}>
        <Heading as='h1' size='4xl' maxW='1080px' m="0 auto">NEXT TODO</Heading>
      </Box>

      <Box maxW='1080px' m='0 auto'>
        <Container w='85%' maxW='1080px' pt='16px'>
          <Box pb="15px" h="63" display="flex" justifyContent="space-between">
            <Heading as='h2' size='2xl' mt="2">NEW TODO</Heading>
            <Button
              bg="yellow.500"
              color="white"
              borderRadius="full"
              w="112px"
              mt="15px"
            >
              Back
            </Button>
        </Box>

          <form>
            <Box w="100%" margin="0 auto">
              <FormControl mb="20px">
                <FormLabel 
                  htmlFor="title" 
                  fontSize='24px'
                  fontWeight='bold'
                  lineHeight={1}
                >
                  TITLE
                </FormLabel>
                <Input
                  id="title"
                  type="text"
                  value=""
                  h="70px"
                  fontSize='20px'
                  rounded='10px'
                  borderColor='blackAlpha.800'
                  placeholder="Text"
                />
              </FormControl>
              <FormControl mb="20px">
                <FormLabel 
                  htmlFor="description" 
                  fontSize='24px'
                  fontWeight='bold'
                  lineHeight={1}
                >
                  DETAIL
                </FormLabel>
                <Textarea 
                  id="description" 
                  value="" 
                  placeholder="Text" 
                  h='320px'
                  rounded='10px'
                  borderColor='blackAlpha.800'
                  fontSize='20px'
                />
              </FormControl>
              <FormControl>
                <FormLabel
                  htmlFor="description" 
                  fontSize='24px'
                  fontWeight='bold'
                  lineHeight={1}
                >
                  PRIORITY
                </FormLabel>
                <RadioGroup value="">
                  <HStack spacing="24px">
                    <Radio value="male">High</Radio>
                    <Radio value="female">Middle</Radio>
                    <Radio value="other">Low</Radio>
                  </HStack>
                </RadioGroup>
              </FormControl>
            </Box>
            <Box display="flex" justifyContent="flex-end">
              <Button
                type="submit"
                box-sizing="border-box"
                bg="yellow.200"
                borderRadius="full"
                w="112px"
              >
                CREATE
              </Button>
            </Box>
          </form>
        </Container>
      </Box>
    </>
  );
};

export default CreateTodo;