// import Head from 'next/head'
// import { 
//   Box, 
//   Button, 
//   Flex, 
//   FormControl, 
//   FormLabel, 
//   Input, 
//   Spacer, 
//   Heading, 
//   Textarea, 
//   Text, 
//   Container 
// } from '@chakra-ui/react';

// const EditTodo =()=>{

//   const [newTitle, setNewTitle] = useState('') //⑥編集後の新タイトルを定義

//   const handleEditTodo = () => {
//     const newArray = todos.map((todo) =>
//     todo.id === editId? {...todo, title:newTitle} : todo)setTodos(newArray)
//     setNewTitle('')
//     setEditId('')
//   }
//   //⑦編集内容をtodoリストの配列に加える関数

//   const handleEditFormChange = () => {
//     setNewTitle(e.target.value)
//   }
//   //①編集用inputの入力した値に応じてstateを更新

//   return(
//     <>
//       <Head>
//         <title>Edit</title>
//         <meta name="description" content="Generated by create next app" />
//       </Head>
      
//       <Box bg='yellow.200' w='100%' p={3}>
//         <Heading as='h1' size='4xl' maxW='1080px' m="0 auto">NEXT TODO</Heading>
//       </Box>
      
//       <Box maxW='1080px' m='0 auto'>
//         <Container w='85%' maxW='1080px' pt='16px'>
//           <Box pb="15px" h="63" display="flex" justifyContent="space-between">
//             <Heading as='h2' size='2xl' mt="2">EDIT TODO</Heading>
//             <Button
//                 bg="yellow.500"
//                 color="white"
//                 borderRadius="full"
//                 w="112px"
//                 mt="15px"
//             >
//                 Back
//             </Button>
//           </Box>

//           <Box>
//           <Box w='100%'>
//             <FormControl mb='20px'>
//               <FormLabel
//                 fontSize='24px'
//                 fontWeight='bold'
//                 lineHeight={1}
//               >
//                 TITLE
//               </FormLabel>
//               <Input
//                 h='70px'
//                 fontSize='20px'
//                 rounded='10px'
//                 type='text'
//                 borderColor='blackAlpha.800'
//                 // placeholder='Github上に静的サイトをホスティングする' 
//                 value={newTitle}
//                 //①新しいタイトルのstateを定義してinputと紐付け
//                 onChange={handleEditFormChange}
//                 //①編集用inputの入力した値に応じてstateを更新する
//               />
//             </FormControl>
//             <FormControl mb='20px'>
//               <FormLabel
//                 fontSize='24px'
//                 fontWeight='bold'
//                 lineHeight={1}
//               >
//                 DETAIL
//               </FormLabel>
//               <Textarea
//                 h='320px'
//                 rounded='10px'
//                 borderColor='blackAlpha.800'
//                 fontSize='20px'
//                 placeholder='AWS コンソールで AWS Amplify を使って静的ウェブサイトをホスティングします。AWS Amplify は、静的ウェブサイトおよびウェブアプリにフルマネージドのホスティングを提供します。Amplify のホスティングソリューションは、Amazon CloudFront と Amazon S3 を使って、AWS コンテンツ配信ネットワーク (CDN) を介してサイトアセットを提供します。'
//               >
//               </Textarea>
//             </FormControl>

//             <Flex mt={1}>
//               <Flex direction ='column' mr={27}>
//                 <Text>Create</Text>
//                 <Text fontSize='20px'>2020-11-8 18:55</Text>
//               </Flex>
//               <Flex direction ='column'>
//                 <Text>Update</Text>
//                 <Text fontSize='20px'>2020-11-8 18:55</Text>
//               </Flex>
//               <Spacer />
//               <Button
//                 w={28}
//                 bg='yellow.200'
//                 rounded='full'
//                 onClick={handleEditTodo}
//                 // ②編集ボタンを押すと関数が実行されるようにする
//               >
//                 UPDATE
//               </Button>
//             </Flex>
//           </Box>
//           </Box>
//         </Container>
//       </Box>
//     </>
//     )
// }
// export default EditTodo;