import { useEffect, useState } from 'react';
import Head from 'next/head'
import {
  Box,
  Heading,
} from "@chakra-ui/react";
import { BackButton } from '../../components/backButton';
import { doc, getDoc } from 'firebase/firestore';
import db from '../../src/firebase';
import { useRouter } from 'next/router';

const TodoShow = () => {

  const router = useRouter();
  const todoId = router.query.id;

  const [title, setTitle] = useState("")
  const [detail, setDetail] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      const docRef = doc(db, "todos", todoId);
      const docSnap = await getDoc(docRef);
      setTitle(docSnap.data().title);
      setDetail(docSnap.data().detail);
      // console.log(docSnap.data().title)
    }; 
    if (todoId) {
      fetchData();
    }
  },[todoId])

  // console.log(detail)

  return (
    <>
      <Head>
        <title>Show</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Box bg='yellow.200' w='100%' p={3}>
        <Heading as='h1' size='4xl' maxW='1080px' m="0 auto">NEXT TODO</Heading>
      </Box>

      <Box maxW="1080px" margin="0 auto">
        <Box mt="3" pb='15px' h='63' display='flex' justifyContent="space-between" >
          <Heading as='h2' size='2xl' mt="2">SHOW TODO</Heading>
          <BackButton />
        </Box>

        <Box w='100%' mt="5">
          <Box mb='20px' borderRadius={"10px"}
          border={"1px"}
          borderColor={"blackAlpha.800"}>
            <Box
              fontSize='24px'
              fontWeight='bold'
              lineHeight={1}
              bg={'yellow.300'}
              textAlign="center"
            >
              TITLE
            </Box>
            <Box
              h='70px'
              fontSize='20px'
              type='text'
              borderColor='blackAlpha.800'
            >
              {title}
            </Box>
          </Box>
          <Box mb='20px' borderRadius={"10px"}
          border={"1px"}
          borderColor={"blackAlpha.800"}>
            <Box
              fontSize='24px'
              fontWeight='bold'
              lineHeight={1}
              bg={'yellow.300'}
              textAlign="center"
            >
              DETAIL
            </Box>
            <Box
              h='320px'
              borderColor='blackAlpha.800'
              fontSize='20px'
            >
              {detail}
            </Box>
          </Box>            
        </Box>
      </Box>       
    </>
  );
};

export default TodoShow;
//   Box,
//   Button,
//   chakra,
//   HStack,
//   VStack,
//   Spacer,
//   Grid,
//   GridItem,
//   Heading,
//   Container,
// } from "@chakra-ui/react";
// import { ComentCards } from "./components/comentCards";
// import { ModalTodoShow } from "./components/modalTodoShow";

// const Todoshow = () => {

//   return (
//     <>
//       <Head>
//         <title>Show</title>
//         <meta name="description" content="Generated by create next app" />
//       </Head>

//       <Box bg='yellow.200' w='100%' p={3}>
//         <Heading as='h1' size='4xl' maxW='1080px' m="0 auto">NEXT TODO</Heading>
//       </Box>

//       <Box maxW='1080px' m='0 auto' position="relative" justifyContent="center">
//         <Container w='95%' maxW='1080px' pt='16px' >

//           <Grid >
//             <Box pb="15px" h="63" display="flex">
//               <Heading as='h2' size='2xl' mt="2">TODO SHOW</Heading>
//               <Spacer />
//               <Button
//                 bg="yellow.200"
//                 borderRadius="full"
//                 w="112px"
//                 mt="15px"
//                 border="1px"
//                 mr="15px"
//               >
//                 Comment
//               </Button>
//               <Button
//                 bg="yellow.500"
//                 color="white"
//                 borderRadius="full"
//                 w="112px"
//                 mt="15px"
//               >
//                 Back
//               </Button>  
//             </Box>

//             {/* Show Table */}
//             <GridItem>
//               <VStack
//                 // position={"absolute"}
//                 w={"592px"}
//                 h={"480px"}
//                 left={"100px"}
//                 top={"144px"}
//                 borderRadius={"10px"}
//                 border={"1px"}
//                 borderColor={"blackAlpha.800"}
//               >
//                 {/* TITLE */}
//                 <Box
//                   // position={"absolute"}
//                   w="560px"
//                   mb="12px"
//                   mt="16px"
//                 >
//                   <Box bgColor={"orange.200"}>
//                     <Box fontWeight="bold">TITLE</Box>
//                   </Box>
//                   <Box>Github上に静的サイトをホスティングする</Box>
//                 </Box>

//                 {/* DETAIL */}
//                 <Box
//                   // position={"absolute"}
//                   w="560px"
//                   h="291px"
//                 >
//                   <Box bgColor={"orange.200"}>
//                     <Box fontWeight="bold">DETAIL</Box>
//                   </Box>
//                   <Box>
//                     AWS コンソールで AWS Amplify
//                     を使って静的ウェブサイトをホスティングします。AWS Amplify
//                     は、静的ウェブサイトおよびウェブアプリにフルマネージドのホスティングを提供します。Amplify
//                     のホスティングソリューションは、Amazon CloudFront と Amazon S3
//                     を使って、AWS コンテンツ配信ネットワーク (CDN)
//                     を介してサイトアセットを提供します。
//                     継続的デプロイをセットアップします。Amplify は、継続的デプロイで
//                     Git
//                     ベースのワークフローを提供します。それにより、コードコミットごとに、サイトに自動的に更新をデプロイすることができます。
//                   </Box>
//                 </Box>

//                 {/* FOOTER */}
//                 <HStack
//                   // position={"absolute"}
//                   w="560px"
//                   h="75px"
//                 >
//                   <ModalTodoShow />
//                   <Spacer />
//                   <Box>
//                     <Box fontWeight="bold" mr="10px">Create</Box>
//                     <Box mr="10px"> 2020-11-8 18:55</Box>
//                   </Box>
//                   <Box>
//                     <Box fontWeight="bold">Update</Box>
//                     <Box> 2020-11-8 18:55</Box>
//                   </Box>
//                 </HStack>
//               </VStack>
//             </GridItem>

//             {/* Comment */}
//             <GridItem>
//               <ComentCards />
//             </GridItem>
//           </Grid>
//         </Container>
//       </Box>

//     </>
//   );
// }

// export default Todoshow;